### ISSUE TITLE
Add adiabatic and air_bondary options to solve adjacency

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/dragonfly-grasshopper#22]
The Dragonfly Room2D Solve Adjacency component should be able to support a lot of the options that are on the Honeybee Solve Adjacency component:

![image](https://user-images.githubusercontent.com/5567574/78056628-732c8a00-7353-11ea-898c-5e70506f8587.png)

**Comment by ayezioro** [comment]
Hi,
Attached a paragraph from [this discussion](https://discourse.ladybug.tools/t/multipe-zones-internal-walls-not-solved/10459/3) in the discourse: 
For setting outdoor walls to adiabatic based on things like orientation _**(as you might do for modeling party walls between buildings that are touching each other**_), this is absolutely do-able but the current dragonfly components don’t have such functionality exposed. If you feel this is a high priority, feel free to open an issue.
thanks,
-A.

**Comment by chriswmackey** [comment]
This has been addressed.
